// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOh4k9o0fT8FuNlAv2pGY-r__CgGAyCxg',
    appId: '1:206534749173:web:58cd08a83ce3bf72facebc',
    messagingSenderId: '206534749173',
    projectId: 'editgo-3aaa3',
    authDomain: 'editgo-3aaa3.firebaseapp.com',
    storageBucket: 'editgo-3aaa3.firebasestorage.app',
    measurementId: 'G-57XWJFHMJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbCWnNCBug29GMT4tohW8C7fFepfHYm2Y',
    appId: '1:206534749173:android:9b0b7989ca2b10e5facebc',
    messagingSenderId: '206534749173',
    projectId: 'editgo-3aaa3',
    storageBucket: 'editgo-3aaa3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASjBlQZFhndpDa6M6d_4STVH5YxMtx7h4',
    appId: '1:206534749173:ios:2b8933dde9fb1aeafacebc',
    messagingSenderId: '206534749173',
    projectId: 'editgo-3aaa3',
    storageBucket: 'editgo-3aaa3.firebasestorage.app',
    iosBundleId: 'com.example.agentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASjBlQZFhndpDa6M6d_4STVH5YxMtx7h4',
    appId: '1:206534749173:ios:2b8933dde9fb1aeafacebc',
    messagingSenderId: '206534749173',
    projectId: 'editgo-3aaa3',
    storageBucket: 'editgo-3aaa3.firebasestorage.app',
    iosBundleId: 'com.example.agentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOh4k9o0fT8FuNlAv2pGY-r__CgGAyCxg',
    appId: '1:206534749173:web:7d5b0a7e4ec98deffacebc',
    messagingSenderId: '206534749173',
    projectId: 'editgo-3aaa3',
    authDomain: 'editgo-3aaa3.firebaseapp.com',
    storageBucket: 'editgo-3aaa3.firebasestorage.app',
    measurementId: 'G-K8QW0BGX48',
  );
}
